//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace printTester.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("printTester.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на xml
        ///version
        ///encoding
        ///id
        ///add
        ///xmlns
        ///http
        ///schemas
        ///microsoft
        ///com
        ///office
        ///customui
        ///tc
        ///tcnamespace
        ///ribbon
        ///false
        ///tabs
        ///tab
        ///visible
        ///tag
        ///group
        ///location
        ///button
        ///size
        ///normal
        ///Reloadbtn
        ///change
        ///to
        ///use
        ///callback
        ///on
        ///all
        ///the
        ///attributes
        ///Viewbtn
        ///menu
        ///Createbtn
        ///feature
        ///Id
        ///name
        ///Word
        ///output
        ///dictionaries
        ///assembly
        ///type
        ///Teamcenter
        ///Client
        ///Excel
        ///large
        ///Markup
        ///Outlook
        ///teamcenter
        ///client
        ///fx
        ///xsd
        ///All
        ///a
        ///wildcard
        ///here
        ///or
        ///none
        ///Fx
        ///Common
        ///Basic
        ///Explorer
        ///box
        ///vertical
        ///Navigation
        ///navs [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string EnglishWords {
            get {
                return ResourceManager.GetString("EnglishWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 
        ///Ф
        ///Т
        ///Илья
        ///С
        ///и
        ///л
        ///х
        ///Д
        ///для
        ///П
        ///бланк
        ///е
        ///учету
        ///Павел
        ///й
        ///ц
        ///Ъ
        ///ы
        ///Ь
        ///письма
        ///филиала
        ///передачи
        ///К
        ///У
        ///АТБ
        ///Н
        ///утверждающий
        ///на
        ///странице
        ///наступлению
        ///у
        ///вышел
        ///хранения
        ///не
        ///в
        ///представлениях
        ///ли
        ///Архивные
        ///захвата
        ///всех
        ///Р
        ///ж
        ///а
        ///г
        ///я
        ///Ч
        ///ю
        ///Ш
        ///И
        ///ш
        ///ч
        ///н
        ///Щ
        ///Г
        ///Я
        ///м
        ///д
        ///Ы
        ///Й
        ///А
        ///З
        ///с
        ///Тт
        ///ф
        ///Б
        ///к
        ///э
        ///б
        ///Е
        ///В
        ///двигателе
        ///Э
        ///УПЗ
        ///Ц
        ///щ
        ///записки
        ///РЛ
        ///ст
        ///КВД
        ///з
        ///М
        ///Л
        ///ъ
        ///выпуска
        ///при
        ///час
        ///результате
        ///части
        ///трещина
        ///аппарата
        ///ступени
        ///лючка
        ///Дмитрий
        ///представитель
        ///группы
        ///ВС
        ///Завершение
        ///ь
        ///РКВ
        ///Ж
        /// [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Words {
            get {
                return ResourceManager.GetString("Words", resourceCulture);
            }
        }
    }
}
